### ISSUE TITLE
Defaults can't be applied to externally-created Request objects

### ISSUE THREAD

**Issue by bryanrsmith** [aurelia/fetch-client#1]
`fetch(input, init)` can accept either a url as the first param with an optional init object for the second, or a single `Request` object if the caller wants to create the `Request` manually. If the caller supplies a url + init, we can merge the configured `defaults` object into the supplied init object before creating the `Request`. If the caller supplies a `Request`, though, that class supplies its own defaults and discards the original init object, so we can't tell which properties were specified by the user (but happen to align with `Request`'s defaults) and which properties were omitted by the user and provided by `Request`. This makes it unsafe to merge our `defaults` into the `Request`.

Example:

```js
client.configure(c => c.withDefaults({ mode: 'same-origin' }));

client.fetch(new Request('test'), { mode: 'cors' });
```

`mode: 'cors'` was explicitly specified, but since that's the default anyways we have no way to know if we should override it with the default of `mode: 'same-origin'`.

1. We could accept and document the limitation. (It's already documented).
2. We could allow certain default properties to act as overrides instead of defaults.
3. We could replace `defaults` with `overrides`.
4. We could support both `defaults` and `overrides`, documenting that you may want to use `overrides` if you manually create `Requests`.

**Comment by timbell** [comment]
I  just tried switching to creating the `Request` manually and I think there are a few problems in `buildRequest` as it stands:

1. The body is copied from the request using `input.blob()` but this returns a `Promise` which is not expected/accepted on `requestInit`.

2. When `source` is a `Request` the `Object.assign` call doesn't pick up any of its properties. (Try doing `var req = new Request("http://foo.com")` followed by `var reqCopy = Object.assign({}, req)`)

I would be for **not** creating a new `Request` when `input` is a `Request` so skipping the general `defaults` but still doing the default headers work (because you can).

**Comment by timbell** [comment]
I added a pull request. Seems to contain historical stuff - sorry about that. And the Travis build fails. I'm still struggling to get Git to do what I want.
