### ISSUE TITLE
problems in safari

### ISSUE THREAD

**Issue by javier-troconis-q2** [aurelia/fetch-client#13]
Hi there, we're having issues using the fetch-client library in safari. It fails as soon as we try to configure the client, please have a look @ http://embed.plnkr.co/wc2GDF for a basic sample. We also tried to configure the library using property setters instead of passing in a lambda expression, but then any subsequent "fetch" operation fails.

Thanks,
Javier.

**Comment by EisenbergEffect** [comment]
@bryanrsmith Could this be related to a missing polyfill? We should find a better way to handle that if it's the case. One solution is to make fetch depend on the polyfill, then implement it as an aurelia plugin..with the plugin's configure method detecting whether native fetch is present of not and loading the polyfill if appropriate. If we don't do that, we should definitely make sure to have very clear documentation on it.

**Comment by bryanrsmith** [comment]
Yep. @javier-troconis-q2 the Fetch API isn't yet supported in Safari, so you'll need to include a polyfill like https://github.com/github/fetch. The aurelia fetch library doesn't include the polyfill at this time.

@EisenbergEffect What do you think is the best way to handle this? I originally left out the polyfill because 1) some environments (electron apps, for example) don't need it, and 2) polyfill implementations differ between node & the browser. If we add a dependency on a browser polyfill it won't work in node. There are universal polyfills, but they're larger... Do you think it's acceptable to just document the need for a polyfill? It should be pretty easy to detect lack of support for fetch & log a helpful message to the console.

**Comment by EisenbergEffect** [comment]
Let's start with the warning message. That will at least help people out in the mean time. I'm not quite sure what real solution should be yet. I know that we do want to support both client and server, especially since we want to have "universal" JS in the end. How much larger are the polyfills that cover both node and browser?

**Comment by nitrog7** [comment]
+1

**Comment by KarlDirck** [comment]
So to be clear, using the https://github.com/github/fetch with Aurelia-http-fetch is supported?  
Additionally, the TypeScript definition for this project lacks references to some obejcts (Request, Response, BufferSource, URLSearchParams,) which if used with whatwg-fetch.d.ts (DefinitelyTyped) has collisions/conflicts.  Some comments, documentation, guidance and/or suggestions would greatly help.  
It seems Http-Client stopped working on many mobile device browsers which is what has prompted my research on this project instead.

**Comment by EisenbergEffect** [comment]
The http client stopped working?! What is wrong with that? @bryanrsmith

**Comment by nitrog7** [comment]
iOS devices use mobile Safari. Since aurelia-http-fetch is not working with Safari, the mobile devices are broken as well. It works in Chrome but not Safari and Firefox. As a workaround, I’m using the fetch polyfill as a replacement.

**Comment by EisenbergEffect** [comment]
Ok I think I got confused. You are just referring to the fact that it's broken without the polyfill. Is that correct?

**Comment by nitrog7** [comment]
Correct. At least in my case. I believe this is the situation for @KarlDirck as well.

**Comment by KarlDirck** [comment]
The aurelia-http-client issue was observed on Android and iOS on Chrome and iOS mobile Safari.  I am happy to help provide more information, if needed.

**Comment by KarlDirck** [comment]
Additionally, I am trying to confirm if the aurelia-fetch-client would have maximum compatibility if used WITH the fetch polyfil from github referenced above.  We have an immenent demo on iO (iPhone) that has to work by COB Tuesday.
Thanks.

**Comment by nitrog7** [comment]
Yes. I can confirm the polyfill works on mobile and desktop browsers.

**Comment by javier-troconis-q2** [comment]
@KarlDirck, just add "import 'fetch';" to the list of imports of your app.js. Also, make sure you have a fetch polyfill installed (https://github.com/github/fetch).

**Comment by KarlDirck** [comment]
Thank you.

**Comment by jeff-h** [comment]
Sorry for such a newbie question, but could someone give me a helping hand on how to include the fetch polyfill (and only if it's needed), and where this code should go inside an Aurelia app?

**Comment by bryanrsmith** [comment]
@jeff-h No problem! You can find instructions at https://github.com/aurelia/fetch-client/tree/master/doc#bring-your-own-polyfill. You can import the polyfill anywhere you like, as long as it's loaded before you try to use aurelia-fetch-client. That could be somewhere like main.js, or it could be in the specific view model or service module that uses aurelia-fetch-client.

**Comment by jeff-h** [comment]
Awesome! Thanks for that, and getting back so quickly! Those docs are exactly what I was hoping for. I didn't even go looking for docs in the fetch-client repo honestly — primarily because I am still being caught by surprise at the extent of the docs already in Aurelia :)
