### ISSUE TITLE
Cannot get HTTP Status code of request which errors

### ISSUE THREAD

**Issue by tomtomau** [aurelia/fetch-client#51]
**Overview of the issue:**
I cannot seem to find any way to catch the HTTP Status code of a request which errors out (i.e. 4XX, 5XX codes). A Gist outlining the issue: https://gist.run/?id=7ef33f0d8f481e45417fa7544f4782fe

**Motivation/Use Case:**
When using the fetch client with an API, the server may reply with status codes which provide some context beyond "error", such as 401 indicating unauthorised, when we might need more of a specifc behaviour (check auth credentials are still valid) rather than just "Failed to fetch, sorry"

---

It appears as if it was previously working as evidenced by some code using `response.status`:

* https://github.com/aurelia/fetch-client/issues/46

**Comment by bryanrsmith** [comment]
The httpstat.us service you're using to generate the 500 response appears to have an invalid SSL cert, so the browser is rejecting the request with a TypeError. If you visit the site using https in your browser and tell Chrome to accept the cert then the gist runs as expected.

**Comment by tomtomau** [comment]
Hi @bryanrsmith,
Thanks for replying to this issue. The same issue exists when you substitute for an API that returns a 500. I replaced the URL with our API that I know returns a 500 and I still cannot access the status key.

**Comment by bryanrsmith** [comment]
What output do you expect to see? Here's what I see, which is what I would expect from the code:

![image](https://cloud.githubusercontent.com/assets/186704/14697483/fe5d18fa-0738-11e6-880e-100169ce78a3.png)

**Comment by tomtomau** [comment]
Hmm, okay. I've fixed up the cert and it is working but when I substitute my own API I still had the issues.

For now, I think the issue lies in that my API is not returning Access-Control-Allow-Origin: * on the header, thus it turns into a network request.

For future people who hit this issue - check your headers on the Response.

Thank you @bryanrsmith

**Comment by bryanrsmith** [comment]
No problem! For error responses you should see the status code in dev tools, and you should see a `Response` instance in the interceptor or continuation. If you see a `TypeError` or other JS error type there's probably another issue.

One other thing I noticed-- your requestError interceptor is returning the `Response` instead of throwing it. That will cause the Promise returned by `HttpClient.prototype.fetch()` to resolve successfully instead of rejecting. Unless your interceptor is recovering from the error you typically will want to rethrow the unsuccessful Response (or use `return Promise.reject(response)`).
