### ISSUE TITLE
Feature Request: Reviver

### ISSUE THREAD

**Issue by davismj** [aurelia/fetch-client#66]
What happened to these bad boys?

```javascript
this.http = new HttpClient().configure(x=> {
  x.withReviver((k,v) => {        
    return typeof v === 'object' ? new Person(v) : v;
  });  
});
```

**Comment by bryanrsmith** [comment]
`HttpClient` is now a fairly thin wrapper around the fetch API, so that configuration doesn't exist. You can accomplish the same result by adding a response interceptor that reads the response body as text and then uses `JSON.parse()` with a reviver.

**Comment by davismj** [comment]
Do you think it would be worth building it in?

**Comment by bryanrsmith** [comment]
My personal preference is to keep the library as small as possible, but perhaps it's a better question for the whole team.

We certainly could include some interceptor implementations in the library to cover common use cases. Or we could put them in a separate script so they're opt-in.

**Comment by EisenbergEffect** [comment]
Let's keep it thin.

**Comment by bdenham** [comment]
The docs need to be updated, then. There are still references to the reviver in aurelia-http-client.

**Comment by EisenbergEffect** [comment]
I think you are confusing the two libraries. The http-client supports a reviver but the fetch-client does not.

**Comment by bdenham** [comment]
Ah, ok. Thanks for the clarification. I’ll look more at why my usage of it in aurelia-http-client wouldn’t work.

**Comment by don-bluelinegrid** [comment]
Why doesn't fetch support a reviver?  
This is not exactly the same as the suggestion to use a responseInterceptor, and it also makes the interface and behaviors between HttpClient and FetchClient more divergent.

The reviver approach seemed a more elegant and commonly useful solution.  

Really, from my perspective there is a problem to be solved of casting data returned from an http call into client model types.  I.e., as described in Patrick's post:
http://patrickwalters.net/my-best-practices-for-aurelia-solving-the-m-in-mvvm/

This is a totally common requirement - I want to make a call to a RESTful service that retrieves either an array of items or a single item, and I want these items to be returned to the caller as instances of a defined model type.  I.e., I make a call to /api/customers, and  I would like the returned array to contain CustomerResource objects that are instances of a model class I've defined. Ideally, this would be integrated directly into the HttpClient and FetchClient, perhaps by specifying the type to be instantiated and the path to the collection of items in the JSON response.  The reviver seemed a fair stop-gap measure in lieu of not having this integrated directly into the http services.  However, having to create response interceptors for this seems to much removed and too much overhead on a repetitive basis, for such a common requirement.  Keep in mind that any given project may define many different model types, with many different http calls to retrieve them.

Is there any room for re-considering a solution for this?

Thanks,
Don

**Comment by davismj** [comment]
Don, I think we need to take up arms in a different forum. https://fetch.spec.whatwg.org/

Fetch seems crippled at best to me. They added promises at the cost of a clean API and important features. But my personal vision of Aurelia excludes this kind of library from start. aurelia-http-client and aurelia-fetch-client are in no way Aurelia specific. Aside from the configure function, they're not even first-class citizens. They're just well written wrappers on existing libraries. aurelia-bundler also falls in this category. The best we should ever expect from these libraries is that they are up to date.

**Comment by don-bluelinegrid** [comment]
@davismj @EisenbergEffect 

Hi Matthew,

Thanks for the response.

I am not terribly attached to the use of Fetch vs. http-client.

However, I do think the Aurelia team itself needs to get internal clarity on this.  About 6-8 months ago, we started a new commercial project here.  Leading up to that I did an evaluation of what was currently available, and we decided to move forward with Aurelia as the framework.  In reading the posts by various Aurelia team members (like Jeremy, Patrick, etc.) as well as the Aurelia docs, it appeared that the Aurelia team was positioning use of the aurelia-fetch-client as a) the best practice in use of the framework, and b) the best path for forward-compatibility (with the assumption that Fetch is the future API).  So, for those reasons I adopted use of aurelia-fetch-client in all of the data services I'm creating (with the exception of file upload, which seems to be unworkable with Fetch).

If the Aurelia team consensus is now that their technology roadmap is to not support or be dependent on Fetch for the foreseeable future, and that their promoted best-practice is to use the aurellia-http-client rather than aurelia-fetch-client, then I don't have a particular problem adapting to that.  And, if the aurelia-http-client is the interface that explicitly supports JSON-to-model ORM-type transformation, then that could be a compelling reason for developers to use that client interface.

I'm not entirely clear on the comments about the vision of Aurelia and its supporting libraries.  The libraries like aurelia-http-client and aurelia-fetch-client are created by the Aurelia team in support of the Aurelia framework.  From the perspective of every developer who uses the Aurelia framework, they are a part of the Aurelia framework, and an essential part.  With a modern JS framework, it's really not the case that an Http library is an optional part of the framework, as no useful application could really be built without such support.  So, developer users of the framework expect Http functionality to be provided with the framework, with a well-tested and well-integrated library; the benefit of using a *framework* like Aurelia versus picking a set of libraries and putting them together ourselves, is that we can expect a well-designed set of functionalities that work well together in one framework.

With regard to the fetch-client vs. http-client question, I do feel strongly that there needs to be a clear and documented Aurelia team communication to the developer community, so that developers don't have a temptation to react to individual comments in JIRA issues, and potentially get frustrated with multiple changes of direction/practices.  It's also worth noting that one of the Aurelia plugins we're using (aurelia-auth) explicitly supports Fetch.

Thanks, and look forward to thoughts from the team on this.

Cheers,
Don

**Comment by davismj** [comment]
> I'm not entirely clear on the comments about the vision of Aurelia and its supporting libraries.

This is just my personal opinion, not the vision or direction of the team.

> With a modern JS framework, it's really not the case that an Http library is an optional part of the framework, as no useful application could really be built without such support. 

Sure. But you have those tools already. aurelia-http-client is a wrapper on XMLHttpRequest, which lives on your browser. You don't need aurelia-http-client to use XMLHttpRequest. It just so happens that the aurelia-http-client has a much nicer API and in this way better designed than XMLHttpRequest. Likewise, aurelia-fetch-client is a wrapper on fetch. You don't need aurelia-fetch-client to use fetch. It just so happens that the aurelia-fetch-client is also better than fetch, for the same reasons.

> With regard to the fetch-client vs. http-client question, I do feel strongly that there needs to be a clear and documented Aurelia team communication to the developer community

Noted. Nothing has changed in that regard. Fetch is still the future. But XMLHttpRequest and therefore aurelia-http-client aren't by any means deprecated. You have options, in case you don't like where the future is going.

I understand that many people are coming to us with a need for a cohesive framework with a recommended setup. I think the instructions you've received are great, and none of my comments in this thread detract from that recommendation. 

Aurelia is still the convention over configuration, standards-based, flexible framework it has always been. One of the advantages of Aurelia is that, for example, if you don't like fetch you're free to swap it out at any time. I, personally, have different preferences than my colleagues. And Aurelia affords me and my colleagues the freedom to do things differently as individual developers.

Also, note that I use both aurelia-http-client and aurelia-fetch-client on various projects, depending on the needs of the particular project. All of my latest projects tend to use fetch, though I still like xhr a little better.
