### ISSUE TITLE
Passing existing config to configure function

### ISSUE THREAD

**Issue by micro-jumbo** [aurelia/fetch-client#74]
When calling `configure(function(config))` the `config` parameter should be passed with values currently configured

**Comment by EisenbergEffect** [comment]
@bryanrsmith What do you think of this?

**Comment by bryanrsmith** [comment]
Sounds reasonable to me.

I'm actually not a fan of allowing reconfiguration at all. My favorite idea for this was actually to make the configuration immutable, and instead of allowing reconfiguration we'd have a simple way to create a new instance (child instance?) whose config was based on the first instance. It would be harder to introduce undesirable side effects when a shared client is reconfigured by one consumer.

I didn't get that idea fleshed out in time for release, though. Since we already allow reconfiguration I have no objection to this change :-)

**Comment by micro-jumbo** [comment]
@EisenbergEffect @bryanrsmith 
can #75 be merged?
