### ISSUE TITLE
Interceptor.responseError question

### ISSUE THREAD

**Issue by niemyjski** [aurelia/fetch-client#93]
I was looking at the interceptor and I was expecting the errorResponse interceptor to be passed the response along with a request. But it appears that it only gets the request.. Is this correct?

https://github.com/aurelia/fetch-client/blob/f3ff594382f6b12b3bcb68f3d01960337c5dbc55/src/interfaces.js#L46

https://github.com/aurelia/fetch-client/blob/7ce5dbbc73af0a7e1dcc3d479a649706241fffbe/dist/aurelia-fetch-client.js#L421

**Comment by EisenbergEffect** [comment]
@bryanrsmith Can you help clarify this?

**Comment by bryanrsmith** [comment]
Sorry, I'm not sure I understand. If `fetch()` rejected then there was no `Response`; only the Error generated by the browser. If you have an earlier interceptor that's rejecting even though a `Response` was returned from `fetch()` it's possible that's swallowing the response.

**Comment by niemyjski** [comment]
Yeah, this is what I was wondering, does a response ever get swallowed? And does it make sense to have both request error and response error if there is only ever going to be a request error as you stated?

**Comment by bryanrsmith** [comment]
> does a response ever get swallowed?

Not by this library, but since interceptors can pass along (or swallow) anything they want, it's possible for an application to register an earlier interceptor that swallows requests before later interceptors run.


> does it make sense to have both request error and response error if there is only ever going to be a request error as you stated?

There are two cases where a response error interceptor would run. 
1. When the Promise returned by the underlying `fetch` request rejects. This happens for things like network errors that prevent the request from completing.
2. When an earlier response interceptor completes with a Promise rejection.

**Comment by jonathaneckman** [comment]
@bryanrsmith if the Response is not provided, what is the recommended way to return a Response from `responseError`? Are we to craft our own like this?

```
responseError(error: any, request: Request): Response {
    //... do stuff with the error...
    return new Response(null, { "status": 500, "statusText": error });
}
```

**Comment by EisenbergEffect** [comment]
Answered.
